version: "3"
services:
  server:
    container_name: kmx-payment-gateway
    image: unoteck/kmx-payment-gateway
    restart: always
    env_file:
      - .env
    ports:
      - 3050:3050
    networks:
      kmx_payment_Local:
        ipv4_address: 172.22.0.100
networks:
  kmx_payment_Local:
    driver: default
    ipam:
      config:
        - subnet: 172.22.0.0/16