version: "3"
services:
  server:
    container_name: kmx-payment-gateway
    image: unoteck/kmx-payment-gateway:dev
    restart: always
    env_file:
      - .env
    ports:
      - 3050:3050
    networks:
      - kmx_payment_Local
networks:
  kmx_payment_Local:
    external: true