version: "3"
services:
  server:
    container_name: kmx-payment-gateway
    image: unoteck/kmx-payment-gateway
    restart: always
    network_mode: "host"
    env_file:
      - .env
    ports:
      - 3050:3050
      - 5880:3050